### ISSUE TITLE
duvida calculo de velocidade.

### ISSUE THREAD

**Issue by arnaldojr** [ghsoares/NAC4#1]
https://github.com/ghsoares/NAC4/blob/2a2e81878c39840f6aea934b268b665013c5e604/circuit.ino#L90

qual o racional para esse calculo?

**Comment by ghsoares** [comment]
Foi um erro, originalmente seria 3.6, pois estou convertendo:
`frequência em metros/segundo => metros/hora = x * 3600`
`metros/hora => km/h => x / 1000.0`, então seria
`metros/segundo => km/h = x * (3600 / 1000)` ou `x * 3.6`
mas quando colocava uma frequência de 13 Hz (aproximadamente 80km/h) na verdade estava retornando metade do esperado, então eu dobrei o multiplicador para 7.12, mas coloquei errado no código

**Comment by arnaldojr** [comment]
show! entendi agora. :)
